-- MySQL Script generated by MySQL Workbench
-- Tue Feb  6 20:24:05 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema golosinas_mailin
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `golosinas_mailin` ;

-- -----------------------------------------------------
-- Schema golosinas_mailin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `golosinas_mailin` DEFAULT CHARACTER SET utf8 ;
USE `golosinas_mailin` ;

-- -----------------------------------------------------
-- Table `golosinas_mailin`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`categorias` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `golosinas_mailin`.`productos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`productos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `descripcion` VARCHAR(255) NULL,
  `en_oferta` TINYINT(1) NULL,
  `precio` DECIMAL NULL,
  `descuento` INT NULL,
  `stock` INT NULL,
  `imagen` VARCHAR(255) NULL,
  `categoria_id` INT NOT NULL,
  `estado` TINYINT(1) NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `categorias`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `golosinas_mailin`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `golosinas_mailin`.`cupones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`cupones` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `codigo` VARCHAR(100) NULL,
  `descuento` INT NULL,
  `estado` TINYINT(1) NULL,
  `fecha_expiracion` DATE NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `golosinas_mailin`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`usuarios` (
  `id` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NULL,
  `avatar` VARCHAR(250) NULL,
  `estado` TINYINT(1) NULL,
  `rol` ENUM('CLIENTE', 'ADMIN') NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;

-- -----------------------------------------------------
-- Table `golosinas_mailin`.`carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `total` DECIMAL NULL,
  `fecha_pedido` DATE NULL,
  `estado` ENUM('CONFIRMADO', 'FACTURADO', 'RETIRADO') NULL,
  `usuario_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `usuarios`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `golosinas_mailin`.`usuarios` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `golosinas_mailin`.`productos_carrito`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `golosinas_mailin`.`productos_carrito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `producto_id` INT NULL,
  `carrito_id` INT NULL,
  `cantidad` INT NULL,
  `subtotal` DECIMAL NULL,
  `cupon_id` INT NULL,
  PRIMARY KEY (`id`),
  CONSTRAINT `productos`
    FOREIGN KEY (`producto_id`)
    REFERENCES `golosinas_mailin`.`productos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `cupones`
    FOREIGN KEY (`cupon_id`)
    REFERENCES `golosinas_mailin`.`cupones` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `carrito`
    FOREIGN KEY (`carrito_id`)
    REFERENCES `golosinas_mailin`.`carrito` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
